PackageIdentifier: SI.Bob
InstallerType: msix
Architecture: x64
InstallerUrl: https://siartifactsstorageprod.blob.core.windows.net/wingetrepo/installers/bob_1.4.0.1_x64.msix
InstallerSha256: d2c7e3a4b5f6c8e9a1b2c3d4e5f60718293a4b5c6d7e8f90123456789abcdef0
